[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
liquidation_program = "3cVSJYSXY3yscUwcxrWR5sqoJ4Mcbu1qrQKRjgXbi5AS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ashutosh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
